#!/bin/sh

hooktype=$(basename $0)
verbose=$(git config hookrunner.verbose)

notify() {
  message=$1
  color=$2
  nocolor='\033[0m'

  case "$color" in
  cyan)
    colorcode='\033[0;36m'
    ;;
  green)
    colorcode='\033[0;32m'
    ;;
  red)
    colorcode='\033[0;31m'
    ;;
  *)
    colorcode=$nocolor
    ;;
  esac

  if [ "$verbose" = "true" ]; then
    printf >&2 "${colorcode}${message}${nocolor}\n"
  fi
}

die() {
  message=$1
  notify "$message" red
  exit 111
}

test -z "$GIT_DIR" && GIT_DIR=$(git rev-parse --git-dir)

if [ -z "$GIT_DIR" ]; then
  die "Can't determine the git dir. Are you sure this is a git repo?"
fi

hookdir=$GIT_DIR/hooks/$hooktype.d
if [ -n "$(find $hookdir -type d -empty)" ]; then
  notify "There are no $hooktype hooks." cyan
  exit 0
fi

for HOOK in $GIT_DIR/hooks/$hooktype.d/*; do
  if [ -x $HOOK ]; then
    $HOOK $*
    if [ "$?" -eq 0 ]; then
      notify "$HOOK succeeded" green
    else
      notify "$HOOK failed with code $?" red
      exit 111
    fi
  else
    notify "$HOOK skipped (not executable)" cyan
  fi
done
